[workspace]
members = [
    "cli",
    "cli_emojies",
    "cli_spinner",
    "lib",
    "crypto",
    "signer",
    "types",
    "utils",
    "rpc_api",
    "explorer_api",
    "trezor_api",
    "ledger_api",
]
