[package]
name = "cli"
version = "0.1.0"
authors = ["Zura Benashvili <zura.benashvili@gmail.com>"]
edition = "2018"

[dependencies]
lib = { path = "../lib" }
structopt = "0.3.21"
console = "0.14.0"
dialoguer = "0.7.1"
thiserror = "1.0.24"
serde_json = "1.0.62"
